resolvers:
    - 1.1.1.1:53
    - 1.0.0.1:53
    - 8.8.8.8:53
    - 8.8.4.4:53
    - 9.9.9.9:53
    - 9.9.9.10:53
    - 77.88.8.8:53
    - 77.88.8.1:53
    - 208.67.222.222:53
    - 208.67.220.220:53
sources:
    - alienvault
    - anubis
    - bufferover
    - certspotter
    - censys
    - chaos
    - chinaz
    - crtsh
    - dnsdumpster
    - hackertarget
    - intelx
    - passivetotal
    - robtex
    - riddler
    - securitytrails
    - shodan
    - spyse
    - sublist3r
    - threatcrowd
    - threatminer
    - virustotal
    - fofa
all-sources:
    - alienvault
    - anubis
    - archiveis
    - binaryedge
    - bufferover
    - censys
    - certspotter
    - chaos
    - commoncrawl
    - crtsh
    - dnsdumpster
    - dnsdb
    - github
    - hackertarget
    - intelx
    - passivetotal
    - rapiddns
    - riddler
    - recon
    - robtex
    - securitytrails
    - shodan
    - sitedossier
    - sonarsearch
    - spyse
    - sublist3r
    - threatbook
    - threatcrowd
    - threatminer
    - virustotal
    - waybackarchive
    - zoomeye
    - fofa
recursive:
    - alienvault
    - binaryedge
    - bufferover
    - certspotter
    - crtsh
    - dnsdumpster
    - hackertarget
    - passivetotal
    - securitytrails
    - sonarsearch
    - sublist3r
    - virustotal
binaryedge: 
  - 3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
censys: 
  - dbcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
certspotter:
  - 34xxxxxxxxxxxxxxxxxxxx
chaos: []
chinaz: []
dnsdb: []
github:
  - ghxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
intelx: 
  - d6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
passivetotal:
  - c5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
recon: []
robtex: []
securitytrails: 
  - 3N2mAxxxxxxxxxxxxxxxxxxxx
shodan: 
  - Uxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - Hyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - d2dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
spyse: 
  - 827edxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
threatbook: []
urlscan: 
  - 0c1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
virustotal: 
  - c4f57edxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - ef7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
zoomeye: 
  - 9F70xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
fofa: []
subfinder-version: "2.4.9"